services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - SECRET_KEY=12345
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
